# Generated by Django 5.0 on 2024-01-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_alter_subscribe_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='options',
            field=models.CharField(choices=[('W', 'Weekly'), ('M', 'Monthly')], default='W', max_length=2),
        ),
    ]
